# This file is used by the jenkins job
unittest:
  rpm_deps: [
      python-cliff, python-requests-mock, python-webtest
  ]

  run: >
      tox --sitepackages -v -epy27 2>&1 | tee ../logs/venv-testrun.log;

pep8:
  rpm_deps: [
      pyflakes, python-flake8
  ]

  run: >
      sudo pip install hacking==0.9.6;
      tox --sitepackages -v -e pep8 2>&1 | tee ../logs/venv-testrun.log;

rpm_deps_common: [
  #   Note 1: The order of packages is important
  #   Note 2: openstack-manila is added for its depencencies, but, we'll remove it later.
  git,
  openstack-manila,
  python-tox,
  gcc,
  python-devel,
  python-pip,
  python-pbr,
  python-mox3,
  python-ddt,
  python-oslo-policy,
  python-oslo-vmware,
  python-testresources,
  python-testscenarios,
  python-barbicanclient
]

rpm_deps_tests_req: [
  python-hacking-0.9.2,
  python-testtools,
  python-babel,
  python-coverage,
  python-psycopg2,
  MySQL-python,
  python-testrepository,
  python-mock,
  python-mox,
  python-oslotest,
  python-tempest-lib,
  python-oslo-sphinx,
  python-fixtures,
  python-subunit,
  python-pep8
]

rpm_deps_7: [
  "{{rpm_deps_tests_req}}",
  "{{rpm_deps_common}}",
  "{{ hostvars[inventory_hostname][tester.name]['rpm_deps'] }}"
]

manila_rpm_remove: [
  openstack-manila
]

manila_virt_run_config:
  run: >
    set -o pipefail;
    sudo rm -Rf .tox;
    truncate --size 0 requirements.txt;
    truncate --size 0 test-requirements.txt;
    export NSS_HASH_ALG_SUPPORT=+MD5;
    export OPENSSL_ENABLE_MD5_VERIFY=1;
    rpm -qa > all-rpms.txt;
    {{ hostvars[inventory_hostname][tester.name]['run'] }}

  archive:
    - ../logs/venv-testrun.log
    - all-rpms.txt
    - requirements.txt
    - test-requirements.txt

### actual test_config: starts here: used by khaleesi ###
### NOTE: test_config.virt must be defined ###
test_config:
  virt:
    RedHat-7:
      setup:
        install: "{{rpm_deps_7}}"
        remove: "{{manila_rpm_remove}}"
      run: "{{manila_virt_run_config.run}}"
      archive: "{{manila_virt_run_config.archive}}"
